# #:kivy 1.11.1
# <Screen2>:

#     but: but    
#     canvas: 
#         Rectangle:
#             source:'Screen2.jpg'
#             pos: self.pos
#             size: self.size

#     Button_Grade10:

#         id: but
#         center_x: root.center_x - 70
#         center_y: root.center_y + 25
        
#     Button_Grade11:

#         id: but
#         center_x: root.center_x - 70
#         center_y: root.center_y - 82
        
#     Button_Grade12:

#         id: but
#         center_x: root.center_x - 70
#         center_y: root.center_y - 182    


# <Button_Grade10>:

#     image: image
#     size: 204 , 204
#     background_color: 0,0,0,0
#     Image: 
#         id: image        
#         size: root.size
#         pos: root.pos
#         source: 'Button_Grade10.PNG'

# <Button_Grade11>:

#     image: image
#     size: 204 , 204
#     background_color: 0,0,0,0
#     Image:
#         id: image
#         size: root.size
#         pos: root.pos
#         source: 'Button_Grade11.PNG' 

# <Button_Grade12>:

#     image: image
#     size: 204 , 204
#     background_color: 0,0,0,0
#     Image:
#         id: image
#         size: root.size
#         pos: root.pos
#         source: 'Button_Grade12.PNG' 


        

