# #:kivy 1.11.1
# <Screen4>:

#     but: but
#     canvas:
#         Rectangle:
#             source: 'Screen4.jpg'
#             pos: self.pos
#             size: self.size

#     Button_AtomicSize:

#         id: but
#         center_x: root.center_x - 40
#         center_y: root.center_y + 47.5

#     Button_IE_EN:

#         id: but
#         center_x: root.center_x - 70
#         center_y: root.center_y - 49

# <Button_AtomicSize>:

#     image: image
#     size: 366 , 366
#     background_color: 0,0,0,0
#     Image: 
#         id: image        
#         size: root.size
#         pos: root.pos
#         source: 'Button_AtomicSize.PNG'

# <Button_IE_EN>:

#     image: image
#     size: 366 , 366
#     background_color: 0,0,0,0
#     Image: 
#         id: image        
#         size: root.size
#         pos: root.pos
#         source: 'Button_IE_EN.PNG'
