#:kivy 1.11.1
# <Screen3>:

#     but: but
#     canvas:
#         Rectangle:
#             source: 'Screen3.jpg'
#             pos: self.pos
#             size: self.size

#     Button_AtomicStructure:

#         id: but
#         center_x: root.center_x - 40
#         center_y: root.center_y + 47.5

#     Button_ElementPropoties:

#         id: but
#         center_x: root.center_x - 36
#         center_y: root.center_y - 33

#     Button_RadioActive:

#         id: but
#         center_x: root.center_x - 0
#         center_y: root.center_y - 111.5

# <Button_AtomicStructure>:

#     image: image
#     size: 366 , 366
#     background_color: 0,0,0,0
#     Image: 
#         id: image        
#         size: root.size
#         pos: root.pos
#         source: 'Button_AtomicStructure.PNG'

# <Button_ElementPropoties>:

#     image: image
#     size: 366 , 366
#     background_color: 0,0,0,0
#     Image: 
#         id: image        
#         size: root.size
#         pos: root.pos
#         source: 'Button_ElementPropoties.PNG'

# <Button_RadioActive>:

#     image: image
#     size: 366 , 366
#     background_color: 0,0,0,0
#     Image: 
#         id: image        
#         size: root.size
#         pos: root.pos
#         source: 'Button_RadioActive.PNG'

