# #:kivy 1.11.1

# <ScreenAtomicSize>:
#     name: 'Screen4_1'

#     canvas:
#         Rectangle:
#             source: 'ScreenAtomicSize.jpg'
#             pos: self.pos
#             size: self.size 

<ElementInput>:

    orienatation: 'vertical'

    TextInput:
        id: ElementInput
        font_size: 150
        size_hint_y: None
        height: 200
        text: ''





